// Code generated by wit-bindgen-go. DO NOT EDIT.

package layertypes

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// TriggerSourceCosmosContractEventShape is used for storage in variant or result types.
type TriggerSourceCosmosContractEventShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(TriggerSourceCosmosContractEvent{})]byte
}

// TriggerDataCosmosContractEventShape is used for storage in variant or result types.
type TriggerDataCosmosContractEventShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(TriggerDataCosmosContractEvent{})]byte
}
