// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package host represents the imported interface "host".
package host

import (
	layertypes "github.com/reecepbcups/wavs-go/wavs/worker/layer-types"
	"go.bytecodealliance.org/cm"
)

// EthChainConfig represents the type alias "host#eth-chain-config".
//
// See [layertypes.EthChainConfig] for more information.
type EthChainConfig = layertypes.EthChainConfig

// CosmosChainConfig represents the type alias "host#cosmos-chain-config".
//
// See [layertypes.CosmosChainConfig] for more information.
type CosmosChainConfig = layertypes.CosmosChainConfig

// LogLevel represents the type alias "host#log-level".
//
// See [layertypes.LogLevel] for more information.
type LogLevel = layertypes.LogLevel

// GetEthChainConfig represents the imported function "get-eth-chain-config".
//
//	get-eth-chain-config: func(chain-name: string) -> option<eth-chain-config>
//
//go:nosplit
func GetEthChainConfig(chainName string) (result cm.Option[EthChainConfig]) {
	chainName0, chainName1 := cm.LowerString(chainName)
	wasmimport_GetEthChainConfig((*uint8)(chainName0), (uint32)(chainName1), &result)
	return
}

// GetCosmosChainConfig represents the imported function "get-cosmos-chain-config".
//
//	get-cosmos-chain-config: func(chain-name: string) -> option<cosmos-chain-config>
//
//go:nosplit
func GetCosmosChainConfig(chainName string) (result cm.Option[CosmosChainConfig]) {
	chainName0, chainName1 := cm.LowerString(chainName)
	wasmimport_GetCosmosChainConfig((*uint8)(chainName0), (uint32)(chainName1), &result)
	return
}

// Log represents the imported function "log".
//
//	log: func(level: log-level, message: string)
//
//go:nosplit
func Log(level LogLevel, message string) {
	level0 := (uint32)(level)
	message0, message1 := cm.LowerString(message)
	wasmimport_Log((uint32)(level0), (*uint8)(message0), (uint32)(message1))
	return
}
